# Generated by Django 4.2 on 2025-02-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_connectionrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectionrequest",
            name="connections",
            field=models.ManyToManyField(blank=True, to="users.connectionrequest"),
        ),
    ]
