# Generated by Django 4.2 on 2025-02-09 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="connections",
            field=models.ManyToManyField(
                blank=True, related_name="user_connections", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
