# Generated by Django 4.2 on 2025-02-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_connections"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendship",
            unique_together={("from_user", "to_user")},
        ),
    ]
