# Generated by Django 4.2 on 2026-05-09 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_friendship_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connectionrequest",
            name="connections",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="connections",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
